export const level1Config = {
  id: 'level-1',
  title: 'LEVEL 1',
  phase: 'DENIAL',
  quote: "It wasn't that bad.",
  unlocks: 'Level 2 - Confusion',
  boss: {
    name: 'test.exe',
    archetype: 'The Denier',
    phrase: "You're exaggerating. It wasn't that serious.",
    hp: 100,
    shieldHp: 30,
  },
  player: {
    hp: 3,
    moveSpeed: 190,
    dashSpeed: 430,
    dashDurationMs: 140,
    dashInvulnerableMs: 320,
    hitInvulnerableMs: 900,
    reviveMs: 650,
    reviveInvulnerableMs: 1400,
  },
  shooting: {
    fireIntervalMs: 180,
    projectileSpeed: 360,
    damage: 3,
    clarityOnHit: 5,
  },
  special: {
    name: 'ZERO CONTACT',
    clarityCost: 100,
    safetyMs: 900,
    shieldDamage: 12,
    bossDamage: 6,
  },
  battleBounds: {
    top: 132,
    bottom: 704,
    left: 24,
    right: 366,
  },
  waves: {
    basicIntervalMs: 1150,
    gaslightingDurationMs: 3200,
    gaslightingIntervalMs: 420,
    gaslightingHpThreshold: 60,
  },
  bubbleTexts: [
    "It wasn't that bad.",
    "You're too sensitive.",
    "You're exaggerating.",
    'We were just talking.',
  ],
};
